version: "3.8"
services:
  nb-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client-dc
    ports: 
      - 3000:3000
    volumes: 
      - './client:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  nb-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dc
    ports:
      - 9000:9000
    volumes:
      - './server:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    